const { catchError } = require('../')

exports.addUser = (req, res, next) => {
    try {

    } catch (err) {

    }
}